// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_data2.proto

package scala.sql.proto;

/**
 * Protobuf type {@code LogData2}
 */
public  final class LogData2 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LogData2)
    LogData2OrBuilder {
private static final long serialVersionUID = 0L;
  // Use LogData2.newBuilder() to construct.
  private LogData2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LogData2() {
    dt_ = "";
    bs_ = "";
    reportTime_ = "";
    itemId_ = 0L;
    itemType_ = 0;
    visitTime_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LogData2(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            dt_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            bs_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            reportTime_ = s;
            break;
          }
          case 72: {

            itemId_ = input.readInt64();
            break;
          }
          case 80: {

            itemType_ = input.readInt32();
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();

            visitTime_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return LogData2Proto.internal_static_LogData2_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return LogData2Proto.internal_static_LogData2_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LogData2.class, Builder.class);
  }

  public static final int DT_FIELD_NUMBER = 1;
  private volatile Object dt_;
  /**
   * <code>string dt = 1;</code>
   */
  public String getDt() {
    Object ref = dt_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dt_ = s;
      return s;
    }
  }
  /**
   * <code>string dt = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDtBytes() {
    Object ref = dt_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BS_FIELD_NUMBER = 2;
  private volatile Object bs_;
  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string bs = 2;</code>
   */
  public String getBs() {
    Object ref = bs_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      bs_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string bs = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBsBytes() {
    Object ref = bs_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      bs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORT_TIME_FIELD_NUMBER = 3;
  private volatile Object reportTime_;
  /**
   * <code>string report_time = 3;</code>
   */
  public String getReportTime() {
    Object ref = reportTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      reportTime_ = s;
      return s;
    }
  }
  /**
   * <code>string report_time = 3;</code>
   */
  public com.google.protobuf.ByteString
      getReportTimeBytes() {
    Object ref = reportTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      reportTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEM_ID_FIELD_NUMBER = 9;
  private long itemId_;
  /**
   * <code>int64 item_id = 9;</code>
   */
  public long getItemId() {
    return itemId_;
  }

  public static final int ITEM_TYPE_FIELD_NUMBER = 10;
  private int itemType_;
  /**
   * <code>int32 item_type = 10;</code>
   */
  public int getItemType() {
    return itemType_;
  }

  public static final int VISIT_TIME_FIELD_NUMBER = 11;
  private volatile Object visitTime_;
  /**
   * <code>string visit_time = 11;</code>
   */
  public String getVisitTime() {
    Object ref = visitTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      visitTime_ = s;
      return s;
    }
  }
  /**
   * <code>string visit_time = 11;</code>
   */
  public com.google.protobuf.ByteString
      getVisitTimeBytes() {
    Object ref = visitTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      visitTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dt_);
    }
    if (!getBsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bs_);
    }
    if (!getReportTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reportTime_);
    }
    if (itemId_ != 0L) {
      output.writeInt64(9, itemId_);
    }
    if (itemType_ != 0) {
      output.writeInt32(10, itemType_);
    }
    if (!getVisitTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, visitTime_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dt_);
    }
    if (!getBsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bs_);
    }
    if (!getReportTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reportTime_);
    }
    if (itemId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, itemId_);
    }
    if (itemType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, itemType_);
    }
    if (!getVisitTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, visitTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LogData2)) {
      return super.equals(obj);
    }
    LogData2 other = (LogData2) obj;

    boolean result = true;
    result = result && getDt()
        .equals(other.getDt());
    result = result && getBs()
        .equals(other.getBs());
    result = result && getReportTime()
        .equals(other.getReportTime());
    result = result && (getItemId()
        == other.getItemId());
    result = result && (getItemType()
        == other.getItemType());
    result = result && getVisitTime()
        .equals(other.getVisitTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DT_FIELD_NUMBER;
    hash = (53 * hash) + getDt().hashCode();
    hash = (37 * hash) + BS_FIELD_NUMBER;
    hash = (53 * hash) + getBs().hashCode();
    hash = (37 * hash) + REPORT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getReportTime().hashCode();
    hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getItemId());
    hash = (37 * hash) + ITEM_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getItemType();
    hash = (37 * hash) + VISIT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getVisitTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LogData2 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LogData2 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LogData2 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LogData2 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LogData2 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LogData2 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LogData2 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LogData2 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LogData2 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LogData2 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LogData2 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LogData2 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LogData2 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LogData2}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LogData2)
      LogData2OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogData2Proto.internal_static_LogData2_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogData2Proto.internal_static_LogData2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LogData2.class, Builder.class);
    }

    // Construct using scala.sql.proto.LogData2.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dt_ = "";

      bs_ = "";

      reportTime_ = "";

      itemId_ = 0L;

      itemType_ = 0;

      visitTime_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return LogData2Proto.internal_static_LogData2_descriptor;
    }

    public LogData2 getDefaultInstanceForType() {
      return LogData2.getDefaultInstance();
    }

    public LogData2 build() {
      LogData2 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public LogData2 buildPartial() {
      LogData2 result = new LogData2(this);
      result.dt_ = dt_;
      result.bs_ = bs_;
      result.reportTime_ = reportTime_;
      result.itemId_ = itemId_;
      result.itemType_ = itemType_;
      result.visitTime_ = visitTime_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LogData2) {
        return mergeFrom((LogData2)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LogData2 other) {
      if (other == LogData2.getDefaultInstance()) return this;
      if (!other.getDt().isEmpty()) {
        dt_ = other.dt_;
        onChanged();
      }
      if (!other.getBs().isEmpty()) {
        bs_ = other.bs_;
        onChanged();
      }
      if (!other.getReportTime().isEmpty()) {
        reportTime_ = other.reportTime_;
        onChanged();
      }
      if (other.getItemId() != 0L) {
        setItemId(other.getItemId());
      }
      if (other.getItemType() != 0) {
        setItemType(other.getItemType());
      }
      if (!other.getVisitTime().isEmpty()) {
        visitTime_ = other.visitTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LogData2 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LogData2) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object dt_ = "";
    /**
     * <code>string dt = 1;</code>
     */
    public String getDt() {
      Object ref = dt_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dt_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dt = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDtBytes() {
      Object ref = dt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dt = 1;</code>
     */
    public Builder setDt(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dt = 1;</code>
     */
    public Builder clearDt() {
      
      dt_ = getDefaultInstance().getDt();
      onChanged();
      return this;
    }
    /**
     * <code>string dt = 1;</code>
     */
    public Builder setDtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dt_ = value;
      onChanged();
      return this;
    }

    private Object bs_ = "";
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     */
    public String getBs() {
      Object ref = bs_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bs_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBsBytes() {
      Object ref = bs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     */
    public Builder setBs(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     */
    public Builder clearBs() {
      
      bs_ = getDefaultInstance().getBs();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     */
    public Builder setBsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bs_ = value;
      onChanged();
      return this;
    }

    private Object reportTime_ = "";
    /**
     * <code>string report_time = 3;</code>
     */
    public String getReportTime() {
      Object ref = reportTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reportTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string report_time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReportTimeBytes() {
      Object ref = reportTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reportTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string report_time = 3;</code>
     */
    public Builder setReportTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reportTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string report_time = 3;</code>
     */
    public Builder clearReportTime() {
      
      reportTime_ = getDefaultInstance().getReportTime();
      onChanged();
      return this;
    }
    /**
     * <code>string report_time = 3;</code>
     */
    public Builder setReportTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reportTime_ = value;
      onChanged();
      return this;
    }

    private long itemId_ ;
    /**
     * <code>int64 item_id = 9;</code>
     */
    public long getItemId() {
      return itemId_;
    }
    /**
     * <code>int64 item_id = 9;</code>
     */
    public Builder setItemId(long value) {
      
      itemId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 item_id = 9;</code>
     */
    public Builder clearItemId() {
      
      itemId_ = 0L;
      onChanged();
      return this;
    }

    private int itemType_ ;
    /**
     * <code>int32 item_type = 10;</code>
     */
    public int getItemType() {
      return itemType_;
    }
    /**
     * <code>int32 item_type = 10;</code>
     */
    public Builder setItemType(int value) {
      
      itemType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 item_type = 10;</code>
     */
    public Builder clearItemType() {
      
      itemType_ = 0;
      onChanged();
      return this;
    }

    private Object visitTime_ = "";
    /**
     * <code>string visit_time = 11;</code>
     */
    public String getVisitTime() {
      Object ref = visitTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        visitTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string visit_time = 11;</code>
     */
    public com.google.protobuf.ByteString
        getVisitTimeBytes() {
      Object ref = visitTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        visitTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string visit_time = 11;</code>
     */
    public Builder setVisitTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      visitTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string visit_time = 11;</code>
     */
    public Builder clearVisitTime() {
      
      visitTime_ = getDefaultInstance().getVisitTime();
      onChanged();
      return this;
    }
    /**
     * <code>string visit_time = 11;</code>
     */
    public Builder setVisitTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      visitTime_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LogData2)
  }

  // @@protoc_insertion_point(class_scope:LogData2)
  private static final LogData2 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LogData2();
  }

  public static LogData2 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LogData2>
      PARSER = new com.google.protobuf.AbstractParser<LogData2>() {
    public LogData2 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogData2(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LogData2> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<LogData2> getParserForType() {
    return PARSER;
  }

  public LogData2 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

