// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_data2.proto

package scala.sql.proto;

public interface LogData2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogData2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dt = 1;</code>
   */
  String getDt();
  /**
   * <code>string dt = 1;</code>
   */
  com.google.protobuf.ByteString
      getDtBytes();

  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string bs = 2;</code>
   */
  String getBs();
  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string bs = 2;</code>
   */
  com.google.protobuf.ByteString
      getBsBytes();

  /**
   * <code>string report_time = 3;</code>
   */
  String getReportTime();
  /**
   * <code>string report_time = 3;</code>
   */
  com.google.protobuf.ByteString
      getReportTimeBytes();

  /**
   * <code>int64 item_id = 9;</code>
   */
  long getItemId();

  /**
   * <code>int32 item_type = 10;</code>
   */
  int getItemType();

  /**
   * <code>string visit_time = 11;</code>
   */
  String getVisitTime();
  /**
   * <code>string visit_time = 11;</code>
   */
  com.google.protobuf.ByteString
      getVisitTimeBytes();
}
