// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_data.proto

package scala.sql.proto;

/**
 * Protobuf type {@code LogData}
 */
public final class LogData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LogData)
    LogDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LogData.newBuilder() to construct.
  private LogData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LogData() {
    dt_ = "";
    bs_ = "";
    reportTime_ = "";
    browserUniqId_ = "";
    osPlant_ = "";
    pageId_ = "";
    pageName_ = "";
    pageParam_ = "";
    visitTime_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new LogData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return LogDataProto.internal_static_LogData_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return LogDataProto.internal_static_LogData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LogData.class, Builder.class);
  }

  public static final int DT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object dt_ = "";
  /**
   * <code>string dt = 1;</code>
   * @return The dt.
   */
  @Override
  public String getDt() {
    Object ref = dt_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dt_ = s;
      return s;
    }
  }
  /**
   * <code>string dt = 1;</code>
   * @return The bytes for dt.
   */
  @Override
  public com.google.protobuf.ByteString
      getDtBytes() {
    Object ref = dt_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object bs_ = "";
  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string bs = 2;</code>
   * @return The bs.
   */
  @Override
  public String getBs() {
    Object ref = bs_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      bs_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string bs = 2;</code>
   * @return The bytes for bs.
   */
  @Override
  public com.google.protobuf.ByteString
      getBsBytes() {
    Object ref = bs_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      bs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORT_TIME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object reportTime_ = "";
  /**
   * <code>string report_time = 3;</code>
   * @return The reportTime.
   */
  @Override
  public String getReportTime() {
    Object ref = reportTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      reportTime_ = s;
      return s;
    }
  }
  /**
   * <code>string report_time = 3;</code>
   * @return The bytes for reportTime.
   */
  @Override
  public com.google.protobuf.ByteString
      getReportTimeBytes() {
    Object ref = reportTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      reportTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BROWSER_UNIQ_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object browserUniqId_ = "";
  /**
   * <code>string browser_uniq_id = 4;</code>
   * @return The browserUniqId.
   */
  @Override
  public String getBrowserUniqId() {
    Object ref = browserUniqId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      browserUniqId_ = s;
      return s;
    }
  }
  /**
   * <code>string browser_uniq_id = 4;</code>
   * @return The bytes for browserUniqId.
   */
  @Override
  public com.google.protobuf.ByteString
      getBrowserUniqIdBytes() {
    Object ref = browserUniqId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      browserUniqId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OS_PLANT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object osPlant_ = "";
  /**
   * <code>string os_plant = 5;</code>
   * @return The osPlant.
   */
  @Override
  public String getOsPlant() {
    Object ref = osPlant_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      osPlant_ = s;
      return s;
    }
  }
  /**
   * <code>string os_plant = 5;</code>
   * @return The bytes for osPlant.
   */
  @Override
  public com.google.protobuf.ByteString
      getOsPlantBytes() {
    Object ref = osPlant_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      osPlant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_ID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile Object pageId_ = "";
  /**
   * <code>string page_id = 6;</code>
   * @return The pageId.
   */
  @Override
  public String getPageId() {
    Object ref = pageId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      pageId_ = s;
      return s;
    }
  }
  /**
   * <code>string page_id = 6;</code>
   * @return The bytes for pageId.
   */
  @Override
  public com.google.protobuf.ByteString
      getPageIdBytes() {
    Object ref = pageId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      pageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_NAME_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile Object pageName_ = "";
  /**
   * <code>string page_name = 7;</code>
   * @return The pageName.
   */
  @Override
  public String getPageName() {
    Object ref = pageName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      pageName_ = s;
      return s;
    }
  }
  /**
   * <code>string page_name = 7;</code>
   * @return The bytes for pageName.
   */
  @Override
  public com.google.protobuf.ByteString
      getPageNameBytes() {
    Object ref = pageName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      pageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_PARAM_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object pageParam_ = "";
  /**
   * <code>string page_param = 8;</code>
   * @return The pageParam.
   */
  @Override
  public String getPageParam() {
    Object ref = pageParam_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      pageParam_ = s;
      return s;
    }
  }
  /**
   * <code>string page_param = 8;</code>
   * @return The bytes for pageParam.
   */
  @Override
  public com.google.protobuf.ByteString
      getPageParamBytes() {
    Object ref = pageParam_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      pageParam_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEM_ID_FIELD_NUMBER = 9;
  private long itemId_ = 0L;
  /**
   * <code>int64 item_id = 9;</code>
   * @return The itemId.
   */
  @Override
  public long getItemId() {
    return itemId_;
  }

  public static final int ITEM_TYPE_FIELD_NUMBER = 10;
  private int itemType_ = 0;
  /**
   * <code>int32 item_type = 10;</code>
   * @return The itemType.
   */
  @Override
  public int getItemType() {
    return itemType_;
  }

  public static final int VISIT_TIME_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile Object visitTime_ = "";
  /**
   * <code>string visit_time = 11;</code>
   * @return The visitTime.
   */
  @Override
  public String getVisitTime() {
    Object ref = visitTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      visitTime_ = s;
      return s;
    }
  }
  /**
   * <code>string visit_time = 11;</code>
   * @return The bytes for visitTime.
   */
  @Override
  public com.google.protobuf.ByteString
      getVisitTimeBytes() {
    Object ref = visitTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      visitTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dt_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bs_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bs_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reportTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reportTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(browserUniqId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, browserUniqId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osPlant_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, osPlant_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pageId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, pageId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pageName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, pageName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pageParam_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pageParam_);
    }
    if (itemId_ != 0L) {
      output.writeInt64(9, itemId_);
    }
    if (itemType_ != 0) {
      output.writeInt32(10, itemType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(visitTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, visitTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dt_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bs_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bs_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reportTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reportTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(browserUniqId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, browserUniqId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osPlant_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, osPlant_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pageId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, pageId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pageName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, pageName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pageParam_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pageParam_);
    }
    if (itemId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, itemId_);
    }
    if (itemType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, itemType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(visitTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, visitTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LogData)) {
      return super.equals(obj);
    }
    LogData other = (LogData) obj;

    if (!getDt()
        .equals(other.getDt())) return false;
    if (!getBs()
        .equals(other.getBs())) return false;
    if (!getReportTime()
        .equals(other.getReportTime())) return false;
    if (!getBrowserUniqId()
        .equals(other.getBrowserUniqId())) return false;
    if (!getOsPlant()
        .equals(other.getOsPlant())) return false;
    if (!getPageId()
        .equals(other.getPageId())) return false;
    if (!getPageName()
        .equals(other.getPageName())) return false;
    if (!getPageParam()
        .equals(other.getPageParam())) return false;
    if (getItemId()
        != other.getItemId()) return false;
    if (getItemType()
        != other.getItemType()) return false;
    if (!getVisitTime()
        .equals(other.getVisitTime())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DT_FIELD_NUMBER;
    hash = (53 * hash) + getDt().hashCode();
    hash = (37 * hash) + BS_FIELD_NUMBER;
    hash = (53 * hash) + getBs().hashCode();
    hash = (37 * hash) + REPORT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getReportTime().hashCode();
    hash = (37 * hash) + BROWSER_UNIQ_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBrowserUniqId().hashCode();
    hash = (37 * hash) + OS_PLANT_FIELD_NUMBER;
    hash = (53 * hash) + getOsPlant().hashCode();
    hash = (37 * hash) + PAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPageId().hashCode();
    hash = (37 * hash) + PAGE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getPageName().hashCode();
    hash = (37 * hash) + PAGE_PARAM_FIELD_NUMBER;
    hash = (53 * hash) + getPageParam().hashCode();
    hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getItemId());
    hash = (37 * hash) + ITEM_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getItemType();
    hash = (37 * hash) + VISIT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getVisitTime().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LogData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LogData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LogData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LogData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LogData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LogData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LogData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LogData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LogData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LogData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LogData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LogData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LogData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LogData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LogData)
      LogDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogDataProto.internal_static_LogData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogDataProto.internal_static_LogData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LogData.class, Builder.class);
    }

    // Construct using scala.sql.proto.LogData.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dt_ = "";
      bs_ = "";
      reportTime_ = "";
      browserUniqId_ = "";
      osPlant_ = "";
      pageId_ = "";
      pageName_ = "";
      pageParam_ = "";
      itemId_ = 0L;
      itemType_ = 0;
      visitTime_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return LogDataProto.internal_static_LogData_descriptor;
    }

    @Override
    public LogData getDefaultInstanceForType() {
      return LogData.getDefaultInstance();
    }

    @Override
    public LogData build() {
      LogData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public LogData buildPartial() {
      LogData result = new LogData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(LogData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.dt_ = dt_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bs_ = bs_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.reportTime_ = reportTime_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.browserUniqId_ = browserUniqId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.osPlant_ = osPlant_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.pageId_ = pageId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.pageName_ = pageName_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.pageParam_ = pageParam_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.itemId_ = itemId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.itemType_ = itemType_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.visitTime_ = visitTime_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LogData) {
        return mergeFrom((LogData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LogData other) {
      if (other == LogData.getDefaultInstance()) return this;
      if (!other.getDt().isEmpty()) {
        dt_ = other.dt_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getBs().isEmpty()) {
        bs_ = other.bs_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getReportTime().isEmpty()) {
        reportTime_ = other.reportTime_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getBrowserUniqId().isEmpty()) {
        browserUniqId_ = other.browserUniqId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getOsPlant().isEmpty()) {
        osPlant_ = other.osPlant_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getPageId().isEmpty()) {
        pageId_ = other.pageId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getPageName().isEmpty()) {
        pageName_ = other.pageName_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getPageParam().isEmpty()) {
        pageParam_ = other.pageParam_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getItemId() != 0L) {
        setItemId(other.getItemId());
      }
      if (other.getItemType() != 0) {
        setItemType(other.getItemType());
      }
      if (!other.getVisitTime().isEmpty()) {
        visitTime_ = other.visitTime_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              bs_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              reportTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              browserUniqId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              osPlant_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              pageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              pageName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              pageParam_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              itemId_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              itemType_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              visitTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object dt_ = "";
    /**
     * <code>string dt = 1;</code>
     * @return The dt.
     */
    public String getDt() {
      Object ref = dt_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dt_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dt = 1;</code>
     * @return The bytes for dt.
     */
    public com.google.protobuf.ByteString
        getDtBytes() {
      Object ref = dt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dt = 1;</code>
     * @param value The dt to set.
     * @return This builder for chaining.
     */
    public Builder setDt(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      dt_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string dt = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDt() {
      dt_ = getDefaultInstance().getDt();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string dt = 1;</code>
     * @param value The bytes for dt to set.
     * @return This builder for chaining.
     */
    public Builder setDtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dt_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object bs_ = "";
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     * @return The bs.
     */
    public String getBs() {
      Object ref = bs_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bs_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     * @return The bytes for bs.
     */
    public com.google.protobuf.ByteString
        getBsBytes() {
      Object ref = bs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     * @param value The bs to set.
     * @return This builder for chaining.
     */
    public Builder setBs(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      bs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBs() {
      bs_ = getDefaultInstance().getBs();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     * @param value The bytes for bs to set.
     * @return This builder for chaining.
     */
    public Builder setBsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object reportTime_ = "";
    /**
     * <code>string report_time = 3;</code>
     * @return The reportTime.
     */
    public String getReportTime() {
      Object ref = reportTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reportTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string report_time = 3;</code>
     * @return The bytes for reportTime.
     */
    public com.google.protobuf.ByteString
        getReportTimeBytes() {
      Object ref = reportTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reportTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string report_time = 3;</code>
     * @param value The reportTime to set.
     * @return This builder for chaining.
     */
    public Builder setReportTime(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      reportTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string report_time = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReportTime() {
      reportTime_ = getDefaultInstance().getReportTime();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string report_time = 3;</code>
     * @param value The bytes for reportTime to set.
     * @return This builder for chaining.
     */
    public Builder setReportTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reportTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private Object browserUniqId_ = "";
    /**
     * <code>string browser_uniq_id = 4;</code>
     * @return The browserUniqId.
     */
    public String getBrowserUniqId() {
      Object ref = browserUniqId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        browserUniqId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string browser_uniq_id = 4;</code>
     * @return The bytes for browserUniqId.
     */
    public com.google.protobuf.ByteString
        getBrowserUniqIdBytes() {
      Object ref = browserUniqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        browserUniqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string browser_uniq_id = 4;</code>
     * @param value The browserUniqId to set.
     * @return This builder for chaining.
     */
    public Builder setBrowserUniqId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      browserUniqId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string browser_uniq_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrowserUniqId() {
      browserUniqId_ = getDefaultInstance().getBrowserUniqId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string browser_uniq_id = 4;</code>
     * @param value The bytes for browserUniqId to set.
     * @return This builder for chaining.
     */
    public Builder setBrowserUniqIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      browserUniqId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private Object osPlant_ = "";
    /**
     * <code>string os_plant = 5;</code>
     * @return The osPlant.
     */
    public String getOsPlant() {
      Object ref = osPlant_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        osPlant_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string os_plant = 5;</code>
     * @return The bytes for osPlant.
     */
    public com.google.protobuf.ByteString
        getOsPlantBytes() {
      Object ref = osPlant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        osPlant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string os_plant = 5;</code>
     * @param value The osPlant to set.
     * @return This builder for chaining.
     */
    public Builder setOsPlant(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      osPlant_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string os_plant = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOsPlant() {
      osPlant_ = getDefaultInstance().getOsPlant();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string os_plant = 5;</code>
     * @param value The bytes for osPlant to set.
     * @return This builder for chaining.
     */
    public Builder setOsPlantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      osPlant_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private Object pageId_ = "";
    /**
     * <code>string page_id = 6;</code>
     * @return The pageId.
     */
    public String getPageId() {
      Object ref = pageId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pageId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string page_id = 6;</code>
     * @return The bytes for pageId.
     */
    public com.google.protobuf.ByteString
        getPageIdBytes() {
      Object ref = pageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string page_id = 6;</code>
     * @param value The pageId to set.
     * @return This builder for chaining.
     */
    public Builder setPageId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      pageId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string page_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageId() {
      pageId_ = getDefaultInstance().getPageId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string page_id = 6;</code>
     * @param value The bytes for pageId to set.
     * @return This builder for chaining.
     */
    public Builder setPageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pageId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private Object pageName_ = "";
    /**
     * <code>string page_name = 7;</code>
     * @return The pageName.
     */
    public String getPageName() {
      Object ref = pageName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pageName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string page_name = 7;</code>
     * @return The bytes for pageName.
     */
    public com.google.protobuf.ByteString
        getPageNameBytes() {
      Object ref = pageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string page_name = 7;</code>
     * @param value The pageName to set.
     * @return This builder for chaining.
     */
    public Builder setPageName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      pageName_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string page_name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageName() {
      pageName_ = getDefaultInstance().getPageName();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string page_name = 7;</code>
     * @param value The bytes for pageName to set.
     * @return This builder for chaining.
     */
    public Builder setPageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pageName_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private Object pageParam_ = "";
    /**
     * <code>string page_param = 8;</code>
     * @return The pageParam.
     */
    public String getPageParam() {
      Object ref = pageParam_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pageParam_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string page_param = 8;</code>
     * @return The bytes for pageParam.
     */
    public com.google.protobuf.ByteString
        getPageParamBytes() {
      Object ref = pageParam_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pageParam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string page_param = 8;</code>
     * @param value The pageParam to set.
     * @return This builder for chaining.
     */
    public Builder setPageParam(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      pageParam_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string page_param = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageParam() {
      pageParam_ = getDefaultInstance().getPageParam();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string page_param = 8;</code>
     * @param value The bytes for pageParam to set.
     * @return This builder for chaining.
     */
    public Builder setPageParamBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pageParam_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private long itemId_ ;
    /**
     * <code>int64 item_id = 9;</code>
     * @return The itemId.
     */
    @Override
    public long getItemId() {
      return itemId_;
    }
    /**
     * <code>int64 item_id = 9;</code>
     * @param value The itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemId(long value) {

      itemId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int64 item_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemId() {
      bitField0_ = (bitField0_ & ~0x00000100);
      itemId_ = 0L;
      onChanged();
      return this;
    }

    private int itemType_ ;
    /**
     * <code>int32 item_type = 10;</code>
     * @return The itemType.
     */
    @Override
    public int getItemType() {
      return itemType_;
    }
    /**
     * <code>int32 item_type = 10;</code>
     * @param value The itemType to set.
     * @return This builder for chaining.
     */
    public Builder setItemType(int value) {

      itemType_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 item_type = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemType() {
      bitField0_ = (bitField0_ & ~0x00000200);
      itemType_ = 0;
      onChanged();
      return this;
    }

    private Object visitTime_ = "";
    /**
     * <code>string visit_time = 11;</code>
     * @return The visitTime.
     */
    public String getVisitTime() {
      Object ref = visitTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        visitTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string visit_time = 11;</code>
     * @return The bytes for visitTime.
     */
    public com.google.protobuf.ByteString
        getVisitTimeBytes() {
      Object ref = visitTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        visitTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string visit_time = 11;</code>
     * @param value The visitTime to set.
     * @return This builder for chaining.
     */
    public Builder setVisitTime(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      visitTime_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string visit_time = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearVisitTime() {
      visitTime_ = getDefaultInstance().getVisitTime();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string visit_time = 11;</code>
     * @param value The bytes for visitTime to set.
     * @return This builder for chaining.
     */
    public Builder setVisitTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      visitTime_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LogData)
  }

  // @@protoc_insertion_point(class_scope:LogData)
  private static final LogData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LogData();
  }

  public static LogData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LogData>
      PARSER = new com.google.protobuf.AbstractParser<LogData>() {
    @Override
    public LogData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LogData> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<LogData> getParserForType() {
    return PARSER;
  }

  @Override
  public LogData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

