// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_data.proto

package scala.sql.proto;

/**
 * Protobuf type {@code LogData}
 */
public  final class LogData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LogData)
    LogDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LogData.newBuilder() to construct.
  private LogData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LogData() {
    dt_ = "";
    bs_ = "";
    reportTime_ = "";
    browserUniqId_ = "";
    osPlant_ = "";
    pageId_ = "";
    pageName_ = "";
    pageParam_ = "";
    itemId_ = 0L;
    itemType_ = 0;
    visitTime_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LogData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            dt_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            bs_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            reportTime_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            browserUniqId_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            osPlant_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            pageId_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            pageName_ = s;
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            pageParam_ = s;
            break;
          }
          case 72: {

            itemId_ = input.readInt64();
            break;
          }
          case 80: {

            itemType_ = input.readInt32();
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();

            visitTime_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return LogDataProto.internal_static_LogData_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return LogDataProto.internal_static_LogData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LogData.class, Builder.class);
  }

  public static final int DT_FIELD_NUMBER = 1;
  private volatile Object dt_;
  /**
   * <code>string dt = 1;</code>
   */
  public String getDt() {
    Object ref = dt_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dt_ = s;
      return s;
    }
  }
  /**
   * <code>string dt = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDtBytes() {
    Object ref = dt_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BS_FIELD_NUMBER = 2;
  private volatile Object bs_;
  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string bs = 2;</code>
   */
  public String getBs() {
    Object ref = bs_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      bs_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string bs = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBsBytes() {
    Object ref = bs_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      bs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORT_TIME_FIELD_NUMBER = 3;
  private volatile Object reportTime_;
  /**
   * <code>string report_time = 3;</code>
   */
  public String getReportTime() {
    Object ref = reportTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      reportTime_ = s;
      return s;
    }
  }
  /**
   * <code>string report_time = 3;</code>
   */
  public com.google.protobuf.ByteString
      getReportTimeBytes() {
    Object ref = reportTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      reportTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BROWSER_UNIQ_ID_FIELD_NUMBER = 4;
  private volatile Object browserUniqId_;
  /**
   * <code>string browser_uniq_id = 4;</code>
   */
  public String getBrowserUniqId() {
    Object ref = browserUniqId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      browserUniqId_ = s;
      return s;
    }
  }
  /**
   * <code>string browser_uniq_id = 4;</code>
   */
  public com.google.protobuf.ByteString
      getBrowserUniqIdBytes() {
    Object ref = browserUniqId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      browserUniqId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OS_PLANT_FIELD_NUMBER = 5;
  private volatile Object osPlant_;
  /**
   * <code>string os_plant = 5;</code>
   */
  public String getOsPlant() {
    Object ref = osPlant_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      osPlant_ = s;
      return s;
    }
  }
  /**
   * <code>string os_plant = 5;</code>
   */
  public com.google.protobuf.ByteString
      getOsPlantBytes() {
    Object ref = osPlant_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      osPlant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_ID_FIELD_NUMBER = 6;
  private volatile Object pageId_;
  /**
   * <code>string page_id = 6;</code>
   */
  public String getPageId() {
    Object ref = pageId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      pageId_ = s;
      return s;
    }
  }
  /**
   * <code>string page_id = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPageIdBytes() {
    Object ref = pageId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      pageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_NAME_FIELD_NUMBER = 7;
  private volatile Object pageName_;
  /**
   * <code>string page_name = 7;</code>
   */
  public String getPageName() {
    Object ref = pageName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      pageName_ = s;
      return s;
    }
  }
  /**
   * <code>string page_name = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPageNameBytes() {
    Object ref = pageName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      pageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_PARAM_FIELD_NUMBER = 8;
  private volatile Object pageParam_;
  /**
   * <code>string page_param = 8;</code>
   */
  public String getPageParam() {
    Object ref = pageParam_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      pageParam_ = s;
      return s;
    }
  }
  /**
   * <code>string page_param = 8;</code>
   */
  public com.google.protobuf.ByteString
      getPageParamBytes() {
    Object ref = pageParam_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      pageParam_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEM_ID_FIELD_NUMBER = 9;
  private long itemId_;
  /**
   * <code>int64 item_id = 9;</code>
   */
  public long getItemId() {
    return itemId_;
  }

  public static final int ITEM_TYPE_FIELD_NUMBER = 10;
  private int itemType_;
  /**
   * <code>int32 item_type = 10;</code>
   */
  public int getItemType() {
    return itemType_;
  }

  public static final int VISIT_TIME_FIELD_NUMBER = 11;
  private volatile Object visitTime_;
  /**
   * <code>string visit_time = 11;</code>
   */
  public String getVisitTime() {
    Object ref = visitTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      visitTime_ = s;
      return s;
    }
  }
  /**
   * <code>string visit_time = 11;</code>
   */
  public com.google.protobuf.ByteString
      getVisitTimeBytes() {
    Object ref = visitTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      visitTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dt_);
    }
    if (!getBsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bs_);
    }
    if (!getReportTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reportTime_);
    }
    if (!getBrowserUniqIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, browserUniqId_);
    }
    if (!getOsPlantBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, osPlant_);
    }
    if (!getPageIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, pageId_);
    }
    if (!getPageNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, pageName_);
    }
    if (!getPageParamBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pageParam_);
    }
    if (itemId_ != 0L) {
      output.writeInt64(9, itemId_);
    }
    if (itemType_ != 0) {
      output.writeInt32(10, itemType_);
    }
    if (!getVisitTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, visitTime_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dt_);
    }
    if (!getBsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bs_);
    }
    if (!getReportTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reportTime_);
    }
    if (!getBrowserUniqIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, browserUniqId_);
    }
    if (!getOsPlantBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, osPlant_);
    }
    if (!getPageIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, pageId_);
    }
    if (!getPageNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, pageName_);
    }
    if (!getPageParamBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pageParam_);
    }
    if (itemId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, itemId_);
    }
    if (itemType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, itemType_);
    }
    if (!getVisitTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, visitTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LogData)) {
      return super.equals(obj);
    }
    LogData other = (LogData) obj;

    boolean result = true;
    result = result && getDt()
        .equals(other.getDt());
    result = result && getBs()
        .equals(other.getBs());
    result = result && getReportTime()
        .equals(other.getReportTime());
    result = result && getBrowserUniqId()
        .equals(other.getBrowserUniqId());
    result = result && getOsPlant()
        .equals(other.getOsPlant());
    result = result && getPageId()
        .equals(other.getPageId());
    result = result && getPageName()
        .equals(other.getPageName());
    result = result && getPageParam()
        .equals(other.getPageParam());
    result = result && (getItemId()
        == other.getItemId());
    result = result && (getItemType()
        == other.getItemType());
    result = result && getVisitTime()
        .equals(other.getVisitTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DT_FIELD_NUMBER;
    hash = (53 * hash) + getDt().hashCode();
    hash = (37 * hash) + BS_FIELD_NUMBER;
    hash = (53 * hash) + getBs().hashCode();
    hash = (37 * hash) + REPORT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getReportTime().hashCode();
    hash = (37 * hash) + BROWSER_UNIQ_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBrowserUniqId().hashCode();
    hash = (37 * hash) + OS_PLANT_FIELD_NUMBER;
    hash = (53 * hash) + getOsPlant().hashCode();
    hash = (37 * hash) + PAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPageId().hashCode();
    hash = (37 * hash) + PAGE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getPageName().hashCode();
    hash = (37 * hash) + PAGE_PARAM_FIELD_NUMBER;
    hash = (53 * hash) + getPageParam().hashCode();
    hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getItemId());
    hash = (37 * hash) + ITEM_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getItemType();
    hash = (37 * hash) + VISIT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getVisitTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LogData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LogData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LogData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LogData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LogData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LogData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LogData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LogData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LogData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LogData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LogData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LogData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LogData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LogData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LogData)
      LogDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogDataProto.internal_static_LogData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogDataProto.internal_static_LogData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LogData.class, Builder.class);
    }

    // Construct using scala.sql.proto.LogData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dt_ = "";

      bs_ = "";

      reportTime_ = "";

      browserUniqId_ = "";

      osPlant_ = "";

      pageId_ = "";

      pageName_ = "";

      pageParam_ = "";

      itemId_ = 0L;

      itemType_ = 0;

      visitTime_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return LogDataProto.internal_static_LogData_descriptor;
    }

    public LogData getDefaultInstanceForType() {
      return LogData.getDefaultInstance();
    }

    public LogData build() {
      LogData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public LogData buildPartial() {
      LogData result = new LogData(this);
      result.dt_ = dt_;
      result.bs_ = bs_;
      result.reportTime_ = reportTime_;
      result.browserUniqId_ = browserUniqId_;
      result.osPlant_ = osPlant_;
      result.pageId_ = pageId_;
      result.pageName_ = pageName_;
      result.pageParam_ = pageParam_;
      result.itemId_ = itemId_;
      result.itemType_ = itemType_;
      result.visitTime_ = visitTime_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LogData) {
        return mergeFrom((LogData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LogData other) {
      if (other == LogData.getDefaultInstance()) return this;
      if (!other.getDt().isEmpty()) {
        dt_ = other.dt_;
        onChanged();
      }
      if (!other.getBs().isEmpty()) {
        bs_ = other.bs_;
        onChanged();
      }
      if (!other.getReportTime().isEmpty()) {
        reportTime_ = other.reportTime_;
        onChanged();
      }
      if (!other.getBrowserUniqId().isEmpty()) {
        browserUniqId_ = other.browserUniqId_;
        onChanged();
      }
      if (!other.getOsPlant().isEmpty()) {
        osPlant_ = other.osPlant_;
        onChanged();
      }
      if (!other.getPageId().isEmpty()) {
        pageId_ = other.pageId_;
        onChanged();
      }
      if (!other.getPageName().isEmpty()) {
        pageName_ = other.pageName_;
        onChanged();
      }
      if (!other.getPageParam().isEmpty()) {
        pageParam_ = other.pageParam_;
        onChanged();
      }
      if (other.getItemId() != 0L) {
        setItemId(other.getItemId());
      }
      if (other.getItemType() != 0) {
        setItemType(other.getItemType());
      }
      if (!other.getVisitTime().isEmpty()) {
        visitTime_ = other.visitTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LogData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LogData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object dt_ = "";
    /**
     * <code>string dt = 1;</code>
     */
    public String getDt() {
      Object ref = dt_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dt_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dt = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDtBytes() {
      Object ref = dt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dt = 1;</code>
     */
    public Builder setDt(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dt = 1;</code>
     */
    public Builder clearDt() {
      
      dt_ = getDefaultInstance().getDt();
      onChanged();
      return this;
    }
    /**
     * <code>string dt = 1;</code>
     */
    public Builder setDtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dt_ = value;
      onChanged();
      return this;
    }

    private Object bs_ = "";
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     */
    public String getBs() {
      Object ref = bs_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bs_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBsBytes() {
      Object ref = bs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     */
    public Builder setBs(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     */
    public Builder clearBs() {
      
      bs_ = getDefaultInstance().getBs();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string bs = 2;</code>
     */
    public Builder setBsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bs_ = value;
      onChanged();
      return this;
    }

    private Object reportTime_ = "";
    /**
     * <code>string report_time = 3;</code>
     */
    public String getReportTime() {
      Object ref = reportTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reportTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string report_time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReportTimeBytes() {
      Object ref = reportTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reportTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string report_time = 3;</code>
     */
    public Builder setReportTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reportTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string report_time = 3;</code>
     */
    public Builder clearReportTime() {
      
      reportTime_ = getDefaultInstance().getReportTime();
      onChanged();
      return this;
    }
    /**
     * <code>string report_time = 3;</code>
     */
    public Builder setReportTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reportTime_ = value;
      onChanged();
      return this;
    }

    private Object browserUniqId_ = "";
    /**
     * <code>string browser_uniq_id = 4;</code>
     */
    public String getBrowserUniqId() {
      Object ref = browserUniqId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        browserUniqId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string browser_uniq_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBrowserUniqIdBytes() {
      Object ref = browserUniqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        browserUniqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string browser_uniq_id = 4;</code>
     */
    public Builder setBrowserUniqId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      browserUniqId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string browser_uniq_id = 4;</code>
     */
    public Builder clearBrowserUniqId() {
      
      browserUniqId_ = getDefaultInstance().getBrowserUniqId();
      onChanged();
      return this;
    }
    /**
     * <code>string browser_uniq_id = 4;</code>
     */
    public Builder setBrowserUniqIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      browserUniqId_ = value;
      onChanged();
      return this;
    }

    private Object osPlant_ = "";
    /**
     * <code>string os_plant = 5;</code>
     */
    public String getOsPlant() {
      Object ref = osPlant_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        osPlant_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string os_plant = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOsPlantBytes() {
      Object ref = osPlant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        osPlant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string os_plant = 5;</code>
     */
    public Builder setOsPlant(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      osPlant_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string os_plant = 5;</code>
     */
    public Builder clearOsPlant() {
      
      osPlant_ = getDefaultInstance().getOsPlant();
      onChanged();
      return this;
    }
    /**
     * <code>string os_plant = 5;</code>
     */
    public Builder setOsPlantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      osPlant_ = value;
      onChanged();
      return this;
    }

    private Object pageId_ = "";
    /**
     * <code>string page_id = 6;</code>
     */
    public String getPageId() {
      Object ref = pageId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pageId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string page_id = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPageIdBytes() {
      Object ref = pageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string page_id = 6;</code>
     */
    public Builder setPageId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string page_id = 6;</code>
     */
    public Builder clearPageId() {
      
      pageId_ = getDefaultInstance().getPageId();
      onChanged();
      return this;
    }
    /**
     * <code>string page_id = 6;</code>
     */
    public Builder setPageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pageId_ = value;
      onChanged();
      return this;
    }

    private Object pageName_ = "";
    /**
     * <code>string page_name = 7;</code>
     */
    public String getPageName() {
      Object ref = pageName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pageName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string page_name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPageNameBytes() {
      Object ref = pageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string page_name = 7;</code>
     */
    public Builder setPageName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pageName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string page_name = 7;</code>
     */
    public Builder clearPageName() {
      
      pageName_ = getDefaultInstance().getPageName();
      onChanged();
      return this;
    }
    /**
     * <code>string page_name = 7;</code>
     */
    public Builder setPageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pageName_ = value;
      onChanged();
      return this;
    }

    private Object pageParam_ = "";
    /**
     * <code>string page_param = 8;</code>
     */
    public String getPageParam() {
      Object ref = pageParam_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pageParam_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string page_param = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPageParamBytes() {
      Object ref = pageParam_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pageParam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string page_param = 8;</code>
     */
    public Builder setPageParam(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pageParam_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string page_param = 8;</code>
     */
    public Builder clearPageParam() {
      
      pageParam_ = getDefaultInstance().getPageParam();
      onChanged();
      return this;
    }
    /**
     * <code>string page_param = 8;</code>
     */
    public Builder setPageParamBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pageParam_ = value;
      onChanged();
      return this;
    }

    private long itemId_ ;
    /**
     * <code>int64 item_id = 9;</code>
     */
    public long getItemId() {
      return itemId_;
    }
    /**
     * <code>int64 item_id = 9;</code>
     */
    public Builder setItemId(long value) {
      
      itemId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 item_id = 9;</code>
     */
    public Builder clearItemId() {
      
      itemId_ = 0L;
      onChanged();
      return this;
    }

    private int itemType_ ;
    /**
     * <code>int32 item_type = 10;</code>
     */
    public int getItemType() {
      return itemType_;
    }
    /**
     * <code>int32 item_type = 10;</code>
     */
    public Builder setItemType(int value) {
      
      itemType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 item_type = 10;</code>
     */
    public Builder clearItemType() {
      
      itemType_ = 0;
      onChanged();
      return this;
    }

    private Object visitTime_ = "";
    /**
     * <code>string visit_time = 11;</code>
     */
    public String getVisitTime() {
      Object ref = visitTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        visitTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string visit_time = 11;</code>
     */
    public com.google.protobuf.ByteString
        getVisitTimeBytes() {
      Object ref = visitTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        visitTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string visit_time = 11;</code>
     */
    public Builder setVisitTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      visitTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string visit_time = 11;</code>
     */
    public Builder clearVisitTime() {
      
      visitTime_ = getDefaultInstance().getVisitTime();
      onChanged();
      return this;
    }
    /**
     * <code>string visit_time = 11;</code>
     */
    public Builder setVisitTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      visitTime_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LogData)
  }

  // @@protoc_insertion_point(class_scope:LogData)
  private static final LogData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LogData();
  }

  public static LogData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LogData>
      PARSER = new com.google.protobuf.AbstractParser<LogData>() {
    public LogData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LogData> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<LogData> getParserForType() {
    return PARSER;
  }

  public LogData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

