// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_data.proto

package scala.sql.proto;

public interface LogDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dt = 1;</code>
   */
  String getDt();
  /**
   * <code>string dt = 1;</code>
   */
  com.google.protobuf.ByteString
      getDtBytes();

  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string bs = 2;</code>
   */
  String getBs();
  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string bs = 2;</code>
   */
  com.google.protobuf.ByteString
      getBsBytes();

  /**
   * <code>string report_time = 3;</code>
   */
  String getReportTime();
  /**
   * <code>string report_time = 3;</code>
   */
  com.google.protobuf.ByteString
      getReportTimeBytes();

  /**
   * <code>string browser_uniq_id = 4;</code>
   */
  String getBrowserUniqId();
  /**
   * <code>string browser_uniq_id = 4;</code>
   */
  com.google.protobuf.ByteString
      getBrowserUniqIdBytes();

  /**
   * <code>string os_plant = 5;</code>
   */
  String getOsPlant();
  /**
   * <code>string os_plant = 5;</code>
   */
  com.google.protobuf.ByteString
      getOsPlantBytes();

  /**
   * <code>string page_id = 6;</code>
   */
  String getPageId();
  /**
   * <code>string page_id = 6;</code>
   */
  com.google.protobuf.ByteString
      getPageIdBytes();

  /**
   * <code>string page_name = 7;</code>
   */
  String getPageName();
  /**
   * <code>string page_name = 7;</code>
   */
  com.google.protobuf.ByteString
      getPageNameBytes();

  /**
   * <code>string page_param = 8;</code>
   */
  String getPageParam();
  /**
   * <code>string page_param = 8;</code>
   */
  com.google.protobuf.ByteString
      getPageParamBytes();

  /**
   * <code>int64 item_id = 9;</code>
   */
  long getItemId();

  /**
   * <code>int32 item_type = 10;</code>
   */
  int getItemType();

  /**
   * <code>string visit_time = 11;</code>
   */
  String getVisitTime();
  /**
   * <code>string visit_time = 11;</code>
   */
  com.google.protobuf.ByteString
      getVisitTimeBytes();
}
